#!/usr/bin/env bash
# ============================================================
# 集中配置 — 所有脚本 source 此文件，config.py 从这里读取
# 环境变量优先，未设置则使用默认值。
#
# 切换数据集:    export PINGMESH_DATA=/new/path
# 切换模型:      export PINGMESH_MODEL_PATH=/new/model
# 切换 NPU:      export PINGMESH_NPU_CARDS=0,1,2,3,4,5,6,7
# ============================================================

# ── 项目根目录 ──
PINGMESH_COMMON_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PINGMESH_DEFAULT_PROJECT_ROOT="$(cd -- "${PINGMESH_COMMON_DIR}/.." && pwd)"
export PINGMESH_PROJECT_ROOT="${PINGMESH_PROJECT_ROOT:-${PINGMESH_DEFAULT_PROJECT_ROOT}}"

# ── 数据路径 ──
export PINGMESH_DATA="${PINGMESH_DATA:-${PINGMESH_PROJECT_ROOT}/data/node/nodes_max_labeled}"
export PINGMESH_RESULTS="${PINGMESH_RESULTS:-${PINGMESH_PROJECT_ROOT}/data/res}"

# ── 权重文件 ──
export PINGMESH_WEIGHTS_MANUAL="${PINGMESH_WEIGHTS_MANUAL:-${PINGMESH_PROJECT_ROOT}/data/weights/classified_alarms/all_alarms.json}"
export PINGMESH_WEIGHTS_LLM="${PINGMESH_WEIGHTS_LLM:-${PINGMESH_PROJECT_ROOT}/data/weights/alarm_weights.json}"

# ── 模型 ──
export PINGMESH_MODEL_PATH="${PINGMESH_MODEL_PATH:-/usr/share/large_language_models/DeepSeek-R1-Distill-Qwen-32B}"

# ── NPU / 推理参数 ──
export PINGMESH_NPU_CARDS="${PINGMESH_NPU_CARDS:-4,5,6,7}"
export PINGMESH_TOP_K="${PINGMESH_TOP_K:-10}"
export PINGMESH_BATCH_SIZE="${PINGMESH_BATCH_SIZE:-8}"
export PINGMESH_PROPAGATION_MAX_CANDIDATE_NODES="${PINGMESH_PROPAGATION_MAX_CANDIDATE_NODES:-80}"
export PINGMESH_PROPAGATION_MAX_PATH_DEPTH="${PINGMESH_PROPAGATION_MAX_PATH_DEPTH:-8}"
export PINGMESH_STAGE1_WEIGHT="${PINGMESH_STAGE1_WEIGHT:-0.5}"
export PINGMESH_TEMPERATURE="${PINGMESH_TEMPERATURE:-0.6}"
export PINGMESH_MAX_TOKENS="${PINGMESH_MAX_TOKENS:-4096}"
export PINGMESH_MAX_MODEL_LEN="${PINGMESH_MAX_MODEL_LEN:-16384}"

# ── PC-STGR Stage 1 (small path-conditioned graph ranker) ──
# The paper experiment uses out-of-fold predictions for scoring and trains one
# final checkpoint on all labeled cases for later label-free inference.
export PINGMESH_NEURAL_DEVICE="${PINGMESH_NEURAL_DEVICE:-auto}"
export PINGMESH_NEURAL_FOLDS="${PINGMESH_NEURAL_FOLDS:-5}"
export PINGMESH_NEURAL_EPOCHS="${PINGMESH_NEURAL_EPOCHS:-120}"
export PINGMESH_NEURAL_PATIENCE="${PINGMESH_NEURAL_PATIENCE:-20}"
export PINGMESH_NEURAL_HIDDEN_DIM="${PINGMESH_NEURAL_HIDDEN_DIM:-64}"
export PINGMESH_NEURAL_HEADS="${PINGMESH_NEURAL_HEADS:-4}"
export PINGMESH_NEURAL_LAYERS="${PINGMESH_NEURAL_LAYERS:-2}"
export PINGMESH_NEURAL_EVENT_EMBEDDING_DIM="${PINGMESH_NEURAL_EVENT_EMBEDDING_DIM:-16}"
export PINGMESH_NEURAL_MAX_EVENTS_PER_DEVICE="${PINGMESH_NEURAL_MAX_EVENTS_PER_DEVICE:-16}"
export PINGMESH_NEURAL_MAX_EVENTS_TOTAL="${PINGMESH_NEURAL_MAX_EVENTS_TOTAL:-1024}"
export PINGMESH_NEURAL_MAX_EVENT_VOCAB="${PINGMESH_NEURAL_MAX_EVENT_VOCAB:-256}"
export PINGMESH_NEURAL_SEED="${PINGMESH_NEURAL_SEED:-42}"
export PINGMESH_NEURAL_STAGE2_TOP_K="${PINGMESH_NEURAL_STAGE2_TOP_K:-5}"

# ── Stage 2 edge-state probability ablation ──
export PINGMESH_PROPAGATION_LABELS_ROOT="${PINGMESH_PROPAGATION_LABELS_ROOT:-${PINGMESH_PROJECT_ROOT}/data/propagation_labels}"
export PINGMESH_EDGE_CLASSIFIER_FOLDS="${PINGMESH_EDGE_CLASSIFIER_FOLDS:-5}"
export PINGMESH_EDGE_CLASSIFIER_EPOCHS="${PINGMESH_EDGE_CLASSIFIER_EPOCHS:-300}"
export PINGMESH_EDGE_CLASSIFIER_PATIENCE="${PINGMESH_EDGE_CLASSIFIER_PATIENCE:-30}"
export PINGMESH_EDGE_CLASSIFIER_LEARNING_RATE="${PINGMESH_EDGE_CLASSIFIER_LEARNING_RATE:-0.03}"
export PINGMESH_EDGE_CLASSIFIER_L2="${PINGMESH_EDGE_CLASSIFIER_L2:-0.001}"
